/**
 * lib/productCatalog.js
 * Static Chewy affiliate product catalog — sourced from the Shop tab in index.html.
 * All links include UTM params: utm_source=dogboy&utm_medium=app&utm_campaign=ai-picks
 */

const BASE = 'https://www.chewy.com/s?query=';
const UTM  = '&utm_source=dogboy&utm_medium=app&utm_campaign=ai-picks';
const url  = (q) => `${BASE}${q}${UTM}`;

export const PRODUCT_CATALOG = [
  // ── Food ──────────────────────────────────────────────────────────────────
  {
    product_id:    'prod_food_puppy',
    name:          'Royal Canin Puppy Dry Dog Food',
    brand:         'Royal Canin',
    category:      'food',
    tags:          ['puppy', 'growth', 'kibble', 'vet-recommended'],
    life_stage:    ['puppy'],
    size_fit:      ['small', 'medium', 'large'],
    avoid_for:     [],
    price_band:    'mid',
    affiliate_url: url('royal+canin+puppy'),
  },
  {
    product_id:    'prod_food_senior',
    name:          "Hill's Science Diet Senior 7+ Dog Food",
    brand:         "Hill's Science Diet",
    category:      'food',
    tags:          ['senior', 'joint-support', 'kibble', 'vet-recommended'],
    life_stage:    ['senior'],
    size_fit:      ['small', 'medium', 'large'],
    avoid_for:     [],
    price_band:    'mid',
    affiliate_url: url('hills+science+diet+senior+dog'),
  },
  {
    product_id:    'prod_food_small_breed',
    name:          "Hill's Science Diet Small & Mini Adult",
    brand:         "Hill's Science Diet",
    category:      'food',
    tags:          ['small-breed', 'kibble', 'vet-recommended'],
    life_stage:    ['adult'],
    size_fit:      ['small'],
    avoid_for:     [],
    price_band:    'mid',
    affiliate_url: url('hills+science+diet+small+mini'),
  },
  {
    product_id:    'prod_food_adult',
    name:          'Purina Pro Plan Complete Essentials Adult',
    brand:         'Purina Pro Plan',
    category:      'food',
    tags:          ['adult', 'high-protein', 'kibble', 'vet-recommended'],
    life_stage:    ['adult'],
    size_fit:      ['small', 'medium', 'large'],
    avoid_for:     [],
    price_band:    'mid',
    affiliate_url: url('purina+pro+plan+adult+dog'),
  },
  {
    product_id:    'prod_food_fresh',
    name:          'Ollie Fresh Dog Food (Custom)',
    brand:         'Ollie',
    category:      'food',
    tags:          ['fresh', 'human-grade', 'portioned', 'premium'],
    life_stage:    ['puppy', 'adult', 'senior'],
    size_fit:      ['small', 'medium', 'large'],
    avoid_for:     [],
    price_band:    'high',
    affiliate_url: url('ollie+fresh+dog+food'),
  },

  // ── Treats ────────────────────────────────────────────────────────────────
  {
    product_id:    'prod_treat_training',
    name:          "Zuke's Mini Naturals Training Treats",
    brand:         "Zuke's",
    category:      'treat',
    tags:          ['training', 'high-value', 'soft', 'low-calorie'],
    life_stage:    ['puppy', 'adult', 'senior'],
    size_fit:      ['small', 'medium', 'large'],
    avoid_for:     [],
    price_band:    'low',
    affiliate_url: url('zukes+mini+naturals+training+treats'),
  },
  {
    product_id:    'prod_treat_dental',
    name:          'Greenies Original Dental Treats',
    brand:         'Greenies',
    category:      'treat',
    tags:          ['dental', 'tartar', 'breath', 'vet-recommended'],
    life_stage:    ['adult', 'senior'],
    size_fit:      ['small', 'medium', 'large'],
    avoid_for:     ['aggressive chewers'],
    price_band:    'mid',
    affiliate_url: url('greenies+dental+treats+dog'),
  },

  // ── Supplements / Health ──────────────────────────────────────────────────
  {
    product_id:    'prod_supp_calming',
    name:          'Zesty Paws Calming Bites',
    brand:         'Zesty Paws',
    category:      'supplement',
    tags:          ['anxiety', 'calming', 'l-theanine', 'chamomile', 'stress'],
    life_stage:    ['adult', 'senior'],
    size_fit:      ['small', 'medium', 'large'],
    avoid_for:     [],
    price_band:    'mid',
    affiliate_url: url('zesty+paws+calming+bites'),
  },
  {
    product_id:    'prod_supp_pheromone_collar',
    name:          'Adaptil Calm Pheromone Collar',
    brand:         'Adaptil',
    category:      'supplement',
    tags:          ['anxiety', 'pheromone', 'calming', 'vet-recommended', 'collar'],
    life_stage:    ['adult', 'senior'],
    size_fit:      ['small', 'medium', 'large'],
    avoid_for:     [],
    price_band:    'mid',
    affiliate_url: url('adaptil+calm+collar+dog'),
  },
  {
    product_id:    'prod_supp_joint',
    name:          'Cosequin Maximum Strength Joint Supplement',
    brand:         'Cosequin',
    category:      'supplement',
    tags:          ['joint', 'glucosamine', 'chondroitin', 'senior', 'large-breed'],
    life_stage:    ['adult', 'senior'],
    size_fit:      ['medium', 'large'],
    avoid_for:     [],
    price_band:    'mid',
    affiliate_url: url('cosequin+joint+supplement+dog'),
  },
  {
    product_id:    'prod_supp_multivitamin',
    name:          'Zesty Paws Multivitamin Bites',
    brand:         'Zesty Paws',
    category:      'supplement',
    tags:          ['multivitamin', 'immune', 'digestion', 'skin', 'coat'],
    life_stage:    ['puppy', 'adult'],
    size_fit:      ['small', 'medium', 'large'],
    avoid_for:     [],
    price_band:    'low',
    affiliate_url: url('zesty+paws+multivitamin+dog'),
  },

  // ── Toys ──────────────────────────────────────────────────────────────────
  {
    product_id:    'prod_toy_kong',
    name:          'KONG Classic Stuffable Dog Toy',
    brand:         'KONG',
    category:      'toy',
    tags:          ['enrichment', 'stuffable', 'chew', 'boredom', 'energetic'],
    life_stage:    ['puppy', 'adult', 'senior'],
    size_fit:      ['small', 'medium', 'large'],
    avoid_for:     [],
    price_band:    'low',
    affiliate_url: url('kong+classic+dog+toy'),
  },
  {
    product_id:    'prod_toy_puzzle_squirrel',
    name:          'Outward Hound Hide-A-Squirrel Puzzle',
    brand:         'Outward Hound',
    category:      'toy',
    tags:          ['puzzle', 'enrichment', 'gentle', 'squeaky', 'chill'],
    life_stage:    ['adult', 'senior'],
    size_fit:      ['small', 'medium', 'large'],
    avoid_for:     ['aggressive chewers'],
    price_band:    'low',
    affiliate_url: url('outward+hound+hide+squirrel'),
  },
  {
    product_id:    'prod_toy_puzzle_brick',
    name:          'Nina Ottosson Dog Brick Puzzle',
    brand:         'Nina Ottosson',
    category:      'toy',
    tags:          ['puzzle', 'enrichment', 'mental-exercise', 'energetic', 'interactive'],
    life_stage:    ['adult'],
    size_fit:      ['small', 'medium', 'large'],
    avoid_for:     [],
    price_band:    'mid',
    affiliate_url: url('nina+ottosson+dog+brick+puzzle'),
  },

  // ── Gear ──────────────────────────────────────────────────────────────────
  {
    product_id:    'prod_gear_harness_small',
    name:          'Puppia Soft Dog Harness',
    brand:         'Puppia',
    category:      'gear',
    tags:          ['harness', 'no-choke', 'lightweight', 'small-breed', 'walking'],
    life_stage:    ['puppy', 'adult', 'senior'],
    size_fit:      ['small'],
    avoid_for:     [],
    price_band:    'low',
    affiliate_url: url('puppia+soft+dog+harness'),
  },
  {
    product_id:    'prod_gear_harness_standard',
    name:          'Ruffwear Front Range Dog Harness',
    brand:         'Ruffwear',
    category:      'gear',
    tags:          ['harness', 'escape-proof', 'durable', 'walking', 'hiking'],
    life_stage:    ['adult'],
    size_fit:      ['medium', 'large'],
    avoid_for:     [],
    price_band:    'high',
    affiliate_url: url('ruffwear+front+range+harness'),
  },
  {
    product_id:    'prod_gear_dental_kit',
    name:          'Arm & Hammer Clinical Dental Kit',
    brand:         'Arm & Hammer',
    category:      'gear',
    tags:          ['dental', 'toothbrush', 'toothpaste', 'oral-health', 'preventive'],
    life_stage:    ['puppy', 'adult', 'senior'],
    size_fit:      ['small', 'medium', 'large'],
    avoid_for:     [],
    price_band:    'low',
    affiliate_url: url('arm+hammer+dog+dental+kit'),
  },
];
